providers:
  - provider: "openai"
    model_name: "gpt-4o"
    api_keys: "${OPENAI_API_KEYS}"
    api_bases: "${OPENAI_API_BASES}"
    api_version: "2024-02-15-preview"
    max_tokens: 4096
    temperature: 0.7
    timeout: 60
    max_retries: 3
    proxy_config:
      http: "${HTTP_PROXY}"
      https: "${HTTPS_PROXY}"

  - provider: "qwen"
    model_name: "qwen-turbo"
    api_keys: "${QWEN_API_KEYS}"
    api_base: "https://dashscope.aliyuncs.com/api/v1"
    max_tokens: 2000
    temperature: 0.7
    timeout: 60
    max_retries: 3

  - provider: "deepseek"
    model_name: "deepseek-chat"
    api_keys: "${DEEPSEEK_API_KEYS}"
    api_base: "https://api.deepseek.com/v1"
    max_tokens: 4096
    temperature: 1.0
    timeout: 60
    max_retries: 3

  - provider: "claude"
    model_name: "anthropic.claude-3-5-sonnet-20241022-v2:0"
    api_keys: "${CLAUDE_ACCESS_KEYS}"
    api_base: "${CLAUDE_SECRET_KEY}"
    region: "us-east-1"
    max_tokens: 4096
    temperature: 0.1
    timeout: 60
    max_retries: 3

  - provider: "gemini"
    model_name: "gemini-2.0-flash-exp"
    api_keys: "${GEMINI_API_KEYS}"
    project_id: "${GEMINI_PROJECT_ID}"
    region: "us-central1"
    max_tokens: 8192
    temperature: 1.0
    timeout: 60
    max_retries: 3
